spring:
  datasource:
    url: jdbc:postgresql://192.168.0.61:5432/ontune
    driver-class-name: org.postgresql.Driver
    username: ontune
    password: ontune

server:
  ssl:
    key-store: ./cert/keystore.p12
    key-store-type: PKCS12
    key-store-password: ontune
    key-alias: test
  port: 8443
  http2:
    enabled: true
  servlet:
    encoding:
      charset: UTF-8
      force: true